// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEJ7zMdUtdksvlKaMoA9lmK-Fdlx4Rnu8',
    appId: '1:959187066468:web:3c6b9a09c47abd5384c971',
    messagingSenderId: '959187066468',
    projectId: 'paradoxo-do-burro-c1ada',
    authDomain: 'paradoxo-do-burro-c1ada.firebaseapp.com',
    storageBucket: 'paradoxo-do-burro-c1ada.firebasestorage.app',
    measurementId: 'G-2ZK4X7T7LQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4HsJ-7QE664ffHJy19s5-Fud61wyFAk0',
    appId: '1:959187066468:android:81b42cef109e06ee84c971',
    messagingSenderId: '959187066468',
    projectId: 'paradoxo-do-burro-c1ada',
    storageBucket: 'paradoxo-do-burro-c1ada.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwtvR4NrV1yB-GsDsHQ8Q2g8JYxkdg7Uc',
    appId: '1:959187066468:ios:00600c22a35d25cc84c971',
    messagingSenderId: '959187066468',
    projectId: 'paradoxo-do-burro-c1ada',
    storageBucket: 'paradoxo-do-burro-c1ada.firebasestorage.app',
    iosBundleId: 'com.example.paradoxoDoBurro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwtvR4NrV1yB-GsDsHQ8Q2g8JYxkdg7Uc',
    appId: '1:959187066468:ios:00600c22a35d25cc84c971',
    messagingSenderId: '959187066468',
    projectId: 'paradoxo-do-burro-c1ada',
    storageBucket: 'paradoxo-do-burro-c1ada.firebasestorage.app',
    iosBundleId: 'com.example.paradoxoDoBurro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEJ7zMdUtdksvlKaMoA9lmK-Fdlx4Rnu8',
    appId: '1:959187066468:web:e5fe606e0dccb77684c971',
    messagingSenderId: '959187066468',
    projectId: 'paradoxo-do-burro-c1ada',
    authDomain: 'paradoxo-do-burro-c1ada.firebaseapp.com',
    storageBucket: 'paradoxo-do-burro-c1ada.firebasestorage.app',
    measurementId: 'G-J2QQ0FJTHE',
  );
}
